import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Noderium Documentation Sidebars
 * 
 * Structure:
 * - Templates: ADR, RFC, PRD, Handoff (internal use, not in navbar)
 * - Introduction: Vision, Pillars, Roadmap
 * - Discovery: Market Research, Strategy
 * - Getting Started: Installation, Quick Start
 */
const sidebars: SidebarsConfig = {
  // Introduction - Vision & Philosophy
  introductionSidebar: [{type: 'autogenerated', dirName: '01-introduction'}],
  
  // Discovery - Market Research & Strategy
  // discoverySidebar: [{type: 'autogenerated', dirName: '02-discovery'}],
  
  // Getting Started - Installation & Quick Start
  gettingStartedSidebar: [{type: 'autogenerated', dirName: '03-getting-started'}],
};

export default sidebars;
