import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Noderium Documentation Sidebars
 * 
 * Structure:
 * - Templates: ADR, RFC, PRD, Handoff (internal use, not in navbar)
 * - Introduction: Vision, Pillars, Roadmap
 * - Development: Theming, Technical Guides
 * - Contributing: Issues, PRs, Labels
 * - Getting Started: Installation, Quick Start
 */
const sidebars: SidebarsConfig = {
  // Introduction - Vision & Philosophy
  introductionSidebar: [{type: 'autogenerated', dirName: '01-introduction'}],
  
  // Discovery - Market Research & Strategy
  // discoverySidebar: [{type: 'autogenerated', dirName: '02-discovery'}],
  
  // Development - Technical Guides & References
  developmentSidebar: [{type: 'autogenerated', dirName: '02-development'}],
  
  // Contributing - Issues, PRs, Labels
  contributingSidebar: [{type: 'autogenerated', dirName: '03-contributing'}],
  
  // Getting Started - Installation & Quick Start
  gettingStartedSidebar: [{type: 'autogenerated', dirName: '04-getting-started'}],
};

export default sidebars;
