name: ðŸ“š Documentation
description: Report documentation issues or suggest improvements
title: "[Docs]: "
labels: ["type: documentation", "status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Improvement ðŸ“
        
        Help us improve our documentation! Use this template to report issues or suggest enhancements.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have searched the [existing issues](https://github.com/leal32b/noderium/issues) to make sure this documentation issue has not been reported yet.
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation does this relate to?
      options:
        - "README"
        - "API Documentation"
        - "Getting Started / Tutorial"
        - "How-to Guide"
        - "Architecture / Design Docs"
        - "Contributing Guide"
        - "Code Comments"
        - "Changelog"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - "Missing - Documentation doesn't exist"
        - "Incorrect - Documentation has errors"
        - "Outdated - Documentation needs updating"
        - "Unclear - Documentation is confusing"
        - "Incomplete - Documentation needs more detail"
        - "Improvement - General enhancement suggestion"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation located? (URL, file path, or section name)
      placeholder: e.g., https://docs.example.com/getting-started or apps/docs/docs/...
    validations:
      required: false

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: If applicable, quote the current documentation content.
      placeholder: |
        > Current documentation says...
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Describe the issue with the current documentation.
      placeholder: |
        - What is missing, incorrect, or unclear?
        - What confusion did it cause?
    validations:
      required: true

  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested Content / Changes
      description: Provide your suggested documentation content or changes.
      placeholder: |
        I suggest changing it to...
        
        Or adding the following:
        ...
    validations:
      required: false

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      multiple: true
      options:
        - "New Users"
        - "Experienced Users"
        - "Contributors"
        - "API Consumers"
        - "Maintainers"
        - "All"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this documentation?
      options:
        - label: I would be willing to write/update this documentation.
          required: false
        - label: I would be willing to review the documentation changes.
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references.
      placeholder: Any other information that might help...
    validations:
      required: false
